language: minimal
services:
  - docker

git:
  depth: 2

matrix:
  include:
  - env:
     - LTS=16.0
  - env:
     - LTS=15.3
  - env:
     - LTS=14.27
  - env:
     - LTS=13.19
  - env:
     - LTS=13.11
  #allow_failures:


install:
  - docker --version

script:
  - docker build . -f Dockerfile --build-arg LTS=${LTS} --tag migamake/stack-build-image:${LTS}
      || exit 1;

after_script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
      travis_wait 30 docker push migamake/stack-build-image:${LTS};
    fi;
