language: minimal
services:
  - docker

git:
  depth: 2

matrix:
  include:
  - env:
     - LTS=15.3
     - LTS=14.27
     - LTS=13.19
     - LTS=13.11
     - LTS=12.26
     - LTS=11.22
     - LTS=9.21
  allow_failures:
    - env:
      - LTS=9.21

install:
  - docker --version

script:
  - docker build . -f Dockerfile --build-arg LTS=${LTS} --tag migamake/stack-build:${LTS}
      || exit 1;

after_script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
      docker push migamake/stack-build:$(echo ${LTS}|cut -f-2 -d.);
    fi;
