language: minimal
services:
  - docker

git:
  depth: 2

matrix:
  include:
  - env:
     - LTS=15.3
  - env:
     - LTS=14.27
  - env:
     - LTS=13.19
  - env:
     - LTS=13.11
  - env:
     - LTS=12.26
  allow_failures:
    - env:
      - LTS=15.3

install:
  - docker --version

script:
  - docker build . -f Dockerfile --build-arg LTS=${LTS} --tag migamake/stack-build-image:${LTS}
      || exit 1;

after_script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
      docker push migamake/stack-build-image:${LTS};
    fi;
